WIKIMEDIA_BEACH_IMAGES = {
    "bondi-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Sydney_%28AU%29%2C_Bondi_Beach_--_2019_--_2349.jpg/960px-Sydney_%28AU%29%2C_Bondi_Beach_--_2019_--_2349.jpg",
        "attribution": "Bondi Beach photo by Dietmar Rabich, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Sydney_(AU),_Bondi_Beach_--_2019_--_2349.jpg",
    },
    "manly-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/2020-10-24_Manly_Beach_3.jpg/960px-2020-10-24_Manly_Beach_3.jpg",
        "attribution": "Manly Beach photo by Maksym Kozlenko, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:2020-10-24_Manly_Beach_3.jpg",
    },
    "shelly-beach-manly": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Looking_over_Shelly_Beach_and_Cabbage_Tree_Bay_in_Sydney.jpg/960px-Looking_over_Shelly_Beach_and_Cabbage_Tree_Bay_in_Sydney.jpg",
        "attribution": "Shelly Beach photo by Hardlinerr, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Looking_over_Shelly_Beach_and_Cabbage_Tree_Bay_in_Sydney.jpg",
    },
    "coogee-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Coogee_Beach_NSW.jpg/960px-Coogee_Beach_NSW.jpg",
        "attribution": "Coogee Beach photo by Simposydney, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Coogee_Beach_NSW.jpg",
    },
    "bronte-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bronte_Beach%2C_north_view_20230224_2.jpg/960px-Bronte_Beach%2C_north_view_20230224_2.jpg",
        "attribution": "Bronte Beach photo by DXR, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Bronte_Beach,_north_view_20230224_2.jpg",
    },
    "balmoral-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Balmoral_Beach_by_Kate_Branch.jpg/960px-Balmoral_Beach_by_Kate_Branch.jpg",
        "attribution": "Balmoral Beach photo by Kate Branch, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Balmoral_Beach_by_Kate_Branch.jpg",
    },
    "palm-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Palm_Beach_NSW.jpg/960px-Palm_Beach_NSW.jpg",
        "attribution": "Palm Beach photo by KSpilling, Public domain, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "Public domain",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Palm_Beach_NSW.jpg",
    },
    "cronulla-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Cronulla_Beach_Sydney_September_2023.jpg/960px-Cronulla_Beach_Sydney_September_2023.jpg",
        "attribution": "Cronulla Beach photo by WatsonKat, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Cronulla_Beach_Sydney_September_2023.jpg",
    },
    "maroubra-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Maroubra_Beach_May_2023.jpg/960px-Maroubra_Beach_May_2023.jpg",
        "attribution": "Maroubra Beach photo by Nick-D, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Maroubra_Beach_May_2023.jpg",
    },
    "clovelly-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Clovelly_1.JPG/960px-Clovelly_1.JPG",
        "attribution": "Clovelly Beach photo by J Bar, CC BY 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Clovelly_1.JPG",
    },
    "tamarama-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Tamarama_Beach_Sydney_2019_01.jpg/960px-Tamarama_Beach_Sydney_2019_01.jpg",
        "attribution": "Tamarama Beach photo by MDRX, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Tamarama_Beach_Sydney_2019_01.jpg",
    },
    "freshwater-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Freshwater_beach_NSW.jpg/960px-Freshwater_beach_NSW.jpg",
        "attribution": "Freshwater Beach photo by Mhsb, Public domain, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "Public domain",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Freshwater_beach_NSW.jpg",
    },
    "dee-why-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Dee_Why_Beach%2C_Sydney_2019.jpg/960px-Dee_Why_Beach%2C_Sydney_2019.jpg",
        "attribution": "Dee Why Beach photo by AvaPine123, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Dee_Why_Beach,_Sydney_2019.jpg",
    },
    "avalon-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Avalon%2Cnew_south_wales.jpg/960px-Avalon%2Cnew_south_wales.jpg",
        "attribution": "Avalon Beach photo by Adam.J.W.C., CC BY 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Avalon,new_south_wales.jpg",
    },
    "whale-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/%281%29Whale_Beach_from_Rayner_Road.jpg/960px-%281%29Whale_Beach_from_Rayner_Road.jpg",
        "attribution": "Whale Beach photo by Sardaka, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:(1)Whale_Beach_from_Rayner_Road.jpg",
    },
    "camp-cove": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Camp_Cove%2C_Sydney.jpg/960px-Camp_Cove%2C_Sydney.jpg",
        "attribution": "Camp Cove photo by Martinvl, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Camp_Cove,_Sydney.jpg",
    },
    "milk-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/AUS_Sydney%2C_Woollahra%2C_Milk_Beach_001.jpg/960px-AUS_Sydney%2C_Woollahra%2C_Milk_Beach_001.jpg",
        "attribution": "Milk Beach photo by -wuppertaler, CC BY 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:AUS_Sydney,_Woollahra,_Milk_Beach_001.jpg",
    },
    "gordons-bay": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gordons_Bay%2C_Sydney_panorama.JPG/960px-Gordons_Bay%2C_Sydney_panorama.JPG",
        "attribution": "Gordons Bay photo by Tea and Toast, CC BY-SA 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Gordons_Bay,_Sydney_panorama.JPG",
    },
    "narrabeen-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/North_Narrabeen_sand.JPG/960px-North_Narrabeen_sand.JPG",
        "attribution": "North Narrabeen photo by Poyt448, Public domain, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "Public domain",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:North_Narrabeen_sand.JPG",
    },
    "north-cronulla-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/North_Cronulla_Beach_1.JPG/960px-North_Cronulla_Beach_1.JPG",
        "attribution": "North Cronulla Beach photo by J Bar, CC BY-SA 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:North_Cronulla_Beach_1.JPG",
    },
    "wanda-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Wanda_Beach_1.JPG/960px-Wanda_Beach_1.JPG",
        "attribution": "Wanda Beach photo by J Bar, CC BY-SA 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Wanda_Beach_1.JPG",
    },
    "nielsen-park-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/%281%29Nielsen_Park_Sydney.jpg/960px-%281%29Nielsen_Park_Sydney.jpg",
        "attribution": "Nielsen Park photo by Sardaka, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:(1)Nielsen_Park_Sydney.jpg",
    },
    "shark-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Nielsen_Park_Port_Jackson.JPG/960px-Nielsen_Park_Port_Jackson.JPG",
        "attribution": "Shark Beach area photo by Poyt448, CC0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Nielsen_Park_Port_Jackson.JPG",
    },
    "long-reef-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Sydney_%28AU%29%2C_Long_Reef_Beach_--_2019_--_2616.jpg/960px-Sydney_%28AU%29%2C_Long_Reef_Beach_--_2019_--_2616.jpg",
        "attribution": "Long Reef Beach photo by Dietmar Rabich, CC BY-SA 4.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 4.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Sydney_(AU),_Long_Reef_Beach_--_2019_--_2616.jpg",
    },
    "mona-vale-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Mona_Vale_Beach_-_panoramio_%281%29.jpg/960px-Mona_Vale_Beach_-_panoramio_%281%29.jpg",
        "attribution": "Mona Vale Beach photo from Panoramio archive, CC BY 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Mona_Vale_Beach_-_panoramio_(1).jpg",
    },
    "newport-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/NewportBeachNSW.jpg/960px-NewportBeachNSW.jpg",
        "attribution": "Newport Beach photo by Winston M. Yang, CC BY-SA 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY-SA 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:NewportBeachNSW.jpg",
    },
    "bilgola-beach": {
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Bilgola_Beach_-_panoramio.jpg/960px-Bilgola_Beach_-_panoramio.jpg",
        "attribution": "Bilgola Beach photo from Panoramio archive, CC BY 3.0, via Wikimedia Commons",
        "image_source": "Wikimedia Commons",
        "image_license": "CC BY 3.0",
        "image_source_url": "https://commons.wikimedia.org/wiki/File:Bilgola_Beach_-_panoramio.jpg",
    },
}
